query home {
  home {
    hero {
      description
      heading
      cta {
        link
        openInNewTab
        text
      }
    }
    about {
      heading
      description
      image {
        alternativeText
        url
      }
      cta {
        link
        text
        openInNewTab
      }
    }
    featuredProducts {
      description
      heading
      featuredProducts {
        documentId
        description
        cta {
          link
          openInNewTab
          text
        }
        image {
          alternativeText
          url
          width
          height
        }
        title
        publishedAt
      }
    }
    banner {
      image {
        alternativeText
        url
        width
        height
      }
      heading
      description
      cta {
        link
        openInNewTab
        text
      }
    }
  }
}
