query home {
  home {
    hero {
      description
      heading
      cta {
        link
        openInNewTab
        text
      }
    }
    about {
      heading
      description
      image {
        alternativeText
        url
      }
      cta {
        link
        text
        openInNewTab
      }
    }
  }
}
